// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 20 May 2020 20:00:43 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "leopard.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

