// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 21 May 2020 13:21:33 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "leopard.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

