// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 04 May 2020 04:31:18 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "leopard.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

