// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 20 May 2020 20:00:43 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package leopard

/*
#cgo LDFLAGS: -L./build -llibleopard -lstdc++
#cgo linux LDFLAGS: -fopenmp -ldl
#cgo linux CFLAGS: -fopenmp -DENABLE_OPENMP
#include "leopard.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Leopardresult as declared in leopard/leopard.h:124
type Leopardresult int32

// Leopardresult enumeration from leopard/leopard.h:124
const (
	LeopardSuccess        Leopardresult = iota
	LeopardNeedmoredata   Leopardresult = -1
	LeopardToomuchdata    Leopardresult = -2
	LeopardInvalidsize    Leopardresult = -3
	LeopardInvalidcounts  Leopardresult = -4
	LeopardInvalidinput   Leopardresult = -5
	LeopardPlatform       Leopardresult = -6
	LeopardCallinitialize Leopardresult = -7
)
