// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 04 May 2020 02:15:25 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package leopard

/*
#cgo LDFLAGS: -L./ -llibleopard -lstdc++
#include "leopard/leopard.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// leopardresult as declared in leopard/leopard.h:124
type leopardresult int32

// leopardresult enumeration from leopard/leopard.h:124
const (
	leopardSuccess        leopardresult = iota
	leopardNeedmoredata   leopardresult = -1
	leopardToomuchdata    leopardresult = -2
	leopardInvalidsize    leopardresult = -3
	leopardInvalidcounts  leopardresult = -4
	leopardInvalidinput   leopardresult = -5
	leopardPlatform       leopardresult = -6
	leopardCallinitialize leopardresult = -7
)
