// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 May 2020 12:21:05 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package leopard provides c-go bindings and a wrapper for the C/C++ Leopard-RS library.
 See https://github.com/catid/leopard for more details on the Leopard-RS library.
 The bindings are generated using https://github.com/xlab/c-for-go.


The manually written wrapper contains the exported methods which users of this package interact with.
*/
package leopard
