// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 04 May 2020 02:25:44 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
leopard
*/
package leopard
