// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 04 May 2020 04:31:18 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package leopard

/*
#cgo LDFLAGS: -L./build -llibleopard -lstdc++
#include "leopard.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
